version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    profiles: [ "localstack" ]
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3,lambda,apigateway,sts,cloudformation,ssm,iam,kms,cloudwatch,dynamodb,events
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - HOSTNAME_EXTERNAL=${LOCALSTACK_HOST}
      - LOCALSTACK_HOSTNAME=127.0.0.1
      - LAMBDA_EXECUTOR=docker-reuse
      - DEBUG=1
      #      - DATA_DIR=/tmp/localstack/data # persist data
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
#      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls
        - awslocal sqs list-queues
      interval: 5s
      timeout: 10s
      retries: 10